disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - type_name

line_length: 150
function_body_length:
  warning: 150
  error: 200
file_length:
  warning: 500
  error: 700
function_parameter_count:
  warning: 10
  error: 15
