language: swift
osx_image: xcode13.4
env:
- DESTINATION="OS=14.0,name=iPhone 11" SCHEME="PagerTabStrip" SDK=iphonesimulator

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage update --platform iOS

script:
- xcodebuild clean build -project PagerTabStrip.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild test -project PagerTabStrip.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
