name: Build and test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: xcodebuild test -project PagerTabStripView.xcodeproj -scheme PagerTabStrip -destination 'platform=iOS Simulator,name=iPhone 14 Pro'
    - name: Run linter
      run: swiftlint
